# Site settings
title: Gou Ninja
description: > # this means to ignore newlines until "baseurl:"
  Let Gou Ninja help you drill your Japanese number listening skills!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gou.ninja/" # the base hostname & protocol for your site
twitter_username: hunterbridges
github_username:  hunterbridges

# Build settings
markdown: kramdown
