# Site settings
title: Gou Ninja
description: > # this means to ignore newlines until "baseurl:"
  The fun and quirky way to drill your Nihongo Numbers!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://gou.ninja/" # the base hostname & protocol for your site
twitter_username: hunterbridges
github_username:  hunterbridges

# Build settings
markdown: kramdown
